version: 2.0
jobs:
  a:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: build
          command: gradle test
      - store_test_results:
          path: build/test-results

  b:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: artifacts
          command: gradle jar
      - store_test_results:
          path: /code/test-results

workflows:
  version: 2
  do_stuff:
    jobs:
      - b:
        requires:
          -a
